-- Identity core: users, roles, MFA factors, audit events.
-- Protocol-specific tables (OAuth2 clients, SAML relying parties, SCIM tokens) are
-- introduced in their respective phases.

CREATE TABLE app_user (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username           VARCHAR(100) NOT NULL UNIQUE,
    email              VARCHAR(320) NOT NULL UNIQUE,
    display_name       VARCHAR(200),
    password_hash      VARCHAR(255),
    enabled            BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    external_id        VARCHAR(255),                 -- SCIM externalId
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE role (
    id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(64) NOT NULL UNIQUE                 -- e.g. ROLE_USER, ROLE_ADMIN
);

CREATE TABLE app_user_role (
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES role(id)      ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE mfa_factor (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    type       VARCHAR(32) NOT NULL,                 -- TOTP, OTT, WEBAUTHN
    secret     VARCHAR(255),                         -- TOTP shared secret (Base32); null otherwise
    label      VARCHAR(120),
    enabled    BOOLEAN NOT NULL DEFAULT FALSE,       -- false until enrollment is verified
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, type)
);

CREATE TABLE audit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    principal   VARCHAR(200),
    type        VARCHAR(64) NOT NULL,                -- AUTH_SUCCESS, AUTH_FAILURE, MFA_*, ...
    detail      TEXT,
    remote_ip   VARCHAR(64),
    success     BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_audit_event_occurred_at ON audit_event (occurred_at);
CREATE INDEX idx_audit_event_principal   ON audit_event (principal);
