#!/usr/bin/env python3
"""
Generate the SimpleSAMLphp (1.x) Service Provider config that points at THIS IdP, so the dockerized
SP in docker-compose.test.yml can complete a real SAML Web SSO against us.

The kenchan0130/simplesamlphp image is vanilla SimpleSAMLphp with no SP env-config, so we mount:
  - scripts/saml-sp/authsources.php          -> defines the 'default-sp' SAML SP authsource
  - scripts/saml-sp/saml20-idp-remote.php    -> our IdP's entityID + SSO URL + signing certificate
  - scripts/saml-sp/config.php               -> the image's own config.php with the session store
                                                flipped phpsession -> sql (sqlite). The default
                                                'phpsession' store cannot load a session by ID, which
                                                breaks IdP-initiated (unsolicited) SSO. Pulled from the
                                                image so it always matches the image version.

Run the IdP first (cd sso-backend && ./gradlew bootRun), then:
    python3 scripts/setup_saml_test.py
    docker compose -f docker-compose.test.yml up -d --force-recreate simplesamlphp
    open http://localhost:8088/simplesaml/   (admin / admin)  -> Test -> default-sp
"""
import os
import re
import subprocess
import sys
import urllib.request

BASE = os.environ.get("SSO_BASE", "http://localhost:9000")
METADATA = f"{BASE}/saml2/idp/metadata"
SP_ENTITY_ID = "urn:test:simplesamlphp"
SP_IMAGE = "kenchan0130/simplesamlphp:latest"
# SQLite lives in /tmp because the image's data dir is root-owned (Apache runs as www-data).
SQL_DSN = "sqlite:/tmp/simplesamlphp-store.sq3"
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts", "saml-sp")


def write_config_php():
    """Pull the image's own config.php and flip the session store to sql (sqlite) so IdP-initiated SSO works."""
    try:
        cfg = subprocess.run(
            ["docker", "run", "--rm", SP_IMAGE, "cat", "/var/www/simplesamlphp/config/config.php"],
            check=True, capture_output=True, text=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as e:
        print(f"WARNING: could not read config.php from {SP_IMAGE} ({e}); skipping — IdP-initiated SSO may fail.")
        return
    cfg = re.sub(r"('store\.type'\s*=>\s*)'phpsession'", r"\1'sql'", cfg, count=1)
    cfg = re.sub(r"('store\.sql\.dsn'\s*=>\s*)'[^']*'", rf"\1'{SQL_DSN}'", cfg, count=1)
    with open(os.path.join(OUT_DIR, "config.php"), "w") as f:
        f.write(cfg)
    print("  config.php   : store.type -> sql (sqlite), enables IdP-initiated SSO")


def fetch_metadata():
    try:
        with urllib.request.urlopen(METADATA, timeout=10) as r:
            return r.read().decode()
    except Exception as e:
        sys.exit(f"ERROR: could not fetch {METADATA} — is the IdP running? ({e})")


def first(pattern, xml, what):
    m = re.search(pattern, xml, re.DOTALL)
    if not m:
        sys.exit(f"ERROR: {what} not found in IdP metadata.")
    return m.group(1).strip()


def main():
    xml = fetch_metadata()
    entity_id = first(r'entityID="([^"]+)"', xml, "IdP entityID")
    sso_url = first(r'<[^>]*SingleSignOnService[^>]*Location="([^"]+)"', xml, "SSO Location")
    cert = "".join(first(r"<[^>]*X509Certificate>(.*?)</[^>]*X509Certificate>", xml, "signing cert").split())

    os.makedirs(OUT_DIR, exist_ok=True)

    authsources = f"""<?php
// Generated by scripts/setup_saml_test.py — SimpleSAMLphp SP pointing at the Mini SSO IdP.
$config = [
    'admin' => ['core:AdminPassword'],
    'default-sp' => [
        'saml:SP',
        'entityID' => '{SP_ENTITY_ID}',
        'idp' => '{entity_id}',
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    ],
];
"""
    idp_remote = f"""<?php
// Generated by scripts/setup_saml_test.py — the Mini SSO IdP as a remote SAML 2.0 IdP.
$metadata['{entity_id}'] = [
    'entityid' => '{entity_id}',
    'SingleSignOnService' => '{sso_url}',
    'certData' => '{cert}',
];
"""
    with open(os.path.join(OUT_DIR, "authsources.php"), "w") as f:
        f.write(authsources)
    with open(os.path.join(OUT_DIR, "saml20-idp-remote.php"), "w") as f:
        f.write(idp_remote)
    write_config_php()

    print(f"Wrote SP config to {OUT_DIR}/")
    print(f"  IdP entityID : {entity_id}")
    print(f"  IdP SSO URL  : {sso_url}")
    print(f"  cert         : {len(cert)} chars")
    print(f"  SP entityID  : {SP_ENTITY_ID}")
    print("\nNext:")
    print("  docker compose -f docker-compose.test.yml up -d --force-recreate simplesamlphp")
    print("  open http://localhost:8088/simplesaml/   (admin / admin)  -> Test -> default-sp")


if __name__ == "__main__":
    main()
